/**
 * This function contains all the logic for a specific feature.
 */
function setupMyExampleFeature() {
    // Find the specific HTML elements this feature needs.
    const appContainer = document.getElementById('app-container');
    const mainTitle = document.getElementById('main-title');

    // If the required elements don't exist, stop to prevent errors.
    if (!appContainer || !mainTitle) {
        console.error("Example feature elements not found!");
        return;
    }

    // Now, you can safely manipulate the elements.
    mainTitle.textContent = "My Awesome Feature";
    appContainer.innerHTML = `
        <p>This content was generated by the 'example.js' module!</p>
        <button id="example-btn" class="mt-4 bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded">
            Click Me
        </button>
    `;

    // Add event listeners for elements created by this feature.
    const exampleButton = document.getElementById('example-btn');
    exampleButton.addEventListener('click', () => {
        alert("Button clicked in the example feature!");
    });
}

/**
 * This is the function that main.js will call.
 * It's "exported" to make it available to other files.
 */
export function initializeExampleFeature() {
    setupMyExampleFeature();
}
